'use client'
import {useEffect,useState} from 'react'
import {MessageCircle,Plus,Trash2,CalendarDays,ExternalLink,CheckCircle2,Copy} from 'lucide-react'
import type {User} from '@supabase/supabase-js'
import {supabase} from '../../lib/supabase'
import type {Product} from '../../lib/types'
type Group={id:string;name:string;invite_url:string;category:string;notes:string;active:boolean}
type Campaign={id:string;group_id:string;product_name:string;message:string;scheduled_at:string;status:'scheduled'|'sent'|'canceled'}
const field='w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm focus:border-emerald-600'
const action='rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white disabled:opacity-50'
const formatDate=(value:string)=>new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})
export default function GroupsPanel({user,products}:{user:User|null;products:Product[]}){
 const [groups,setGroups]=useState<Group[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('')
 const [form,setForm]=useState({name:'',invite_url:'',category:'Achadinhos',notes:''})
 const [selectedGroups,setSelectedGroups]=useState<string[]>([]),[productId,setProductId]=useState(''),[copy,setCopy]=useState(''),[when,setWhen]=useState(''),[saving,setSaving]=useState(false)
 const reload=async()=>{if(!supabase||!user)return;setLoading(true);const [g,c]=await Promise.all([supabase.from('whatsapp_groups').select('id,name,invite_url,category,notes,active').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('whatsapp_campaigns').select('id,group_id,product_name,message,scheduled_at,status').eq('user_id',user.id).order('scheduled_at',{ascending:true})]);if(g.error||c.error)setMessage(g.error?.message||c.error?.message||'Falha ao carregar');else{setGroups(g.data||[]);setCampaigns((c.data||[]) as Campaign[])}setLoading(false)}
 useEffect(()=>{if(user)void reload();else{setGroups([]);setCampaigns([])}},[user?.id])
 const addGroup=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!user)return;setMessage('');if(!/^https:\/\/chat\.whatsapp\.com\/[A-Za-z0-9_-]{10,}$/.test(form.invite_url.trim())){setMessage('Informe um link de convite válido do WhatsApp.');return}setSaving(true);const {error}=await supabase.from('whatsapp_groups').insert({...form,name:form.name.trim(),invite_url:form.invite_url.trim(),user_id:user.id});setSaving(false);if(error)setMessage(error.message);else{setForm({name:'',invite_url:'',category:'Achadinhos',notes:''});setMessage('Grupo cadastrado.');void reload()}}
 const deleteGroup=async(g:Group)=>{if(!supabase||!user||!confirm('Excluir '+g.name+' e todos os seus agendamentos?'))return;const {error}=await supabase.from('whatsapp_groups').delete().eq('id',g.id).eq('user_id',user.id);if(error)setMessage(error.message);else void reload()}
 const toggleGroup=async(g:Group)=>{if(!supabase||!user)return;const {error}=await supabase.from('whatsapp_groups').update({active:!g.active}).eq('id',g.id).eq('user_id',user.id);if(error)setMessage(error.message);else void reload()}
 const chooseProduct=(id:string)=>{setProductId(id);const p=products.find(p=>p.id===id);setCopy(p?'🔥 *'+p.name+'*\n\n💰 *'+new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(p.price)+'*\n🛒 Confira: '+(p.id.startsWith('demo-')?'[Produto de demonstração: sem link real]':p.url)+'\n\nPreços e disponibilidade podem mudar.':'')}
 const schedule=async()=>{if(!supabase||!user)return;setMessage('');const p=products.find(p=>p.id===productId);if(!p||!copy.trim()||!selectedGroups.length||!when){setMessage('Escolha produto, grupos, mensagem e horário.');return}const time=new Date(when);if(!Number.isFinite(time.getTime())||time.getTime()<=Date.now()){setMessage('Escolha uma data e horário futuros.');return}if(!confirm('Criar '+selectedGroups.length+' agendamento(s)? O envio será manual.'))return;setSaving(true);const {error}=await supabase.from('whatsapp_campaigns').insert(selectedGroups.map(group_id=>({user_id:user.id,group_id,product_name:p.name,message:copy.trim(),scheduled_at:time.toISOString(),status:'scheduled'})));setSaving(false);if(error)setMessage(error.message);else{setMessage('Agendamentos salvos. O WhatsApp não enviará mensagens automaticamente.');setSelectedGroups([]);void reload()}}
 const updateCampaign=async(c:Campaign,status:'sent'|'canceled')=>{if(!supabase||!user)return;const {error}=await supabase.from('whatsapp_campaigns').update({status}).eq('id',c.id).eq('user_id',user.id);if(error)setMessage(error.message);else void reload()}
 if(!user)return <section className="zap-card rounded-2xl bg-white p-8"><MessageCircle size={32} className="text-emerald-700"/><h2 className="mt-4 text-2xl font-black">Sua central de grupos</h2><p className="mt-2 text-slate-500">Entre na sua conta para cadastrar e gerenciar seus grupos de forma privada.</p></section>
 return <div className="space-y-6"><div className="rounded-[26px] bg-gradient-to-br from-[#0b322b] to-[#247c58] p-7 text-white"><p className="text-xs font-bold tracking-[.2em] text-lime-200">WHATSAPP STUDIO</p><h2 className="mt-3 text-3xl font-black">Seus grupos. Suas campanhas.</h2><p className="mt-3 max-w-xl text-sm text-white/75">Cadastre grupos, prepare mensagens e organize seus envios. Nesta versão, você compartilha manualmente no WhatsApp.</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-xl bg-white/15 px-4 py-3 text-sm">{groups.length} grupos</span><span className="rounded-xl bg-white/15 px-4 py-3 text-sm">{campaigns.filter(c=>c.status==='scheduled').length} agendamentos</span></div></div>
 {message&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}
 <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><section className="zap-card rounded-2xl bg-white p-6"><h3 className="text-lg font-black">Cadastrar grupo</h3><p className="mb-5 mt-1 text-sm text-slate-500">Use o link de convite de um grupo que você administra ou tem autorização para divulgar.</p><form onSubmit={addGroup} className="space-y-3"><label className="block text-sm font-semibold">Nome<input required minLength={2} maxLength={100} className={field+' mt-1'} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Achadinhos da Shopee"/></label><label className="block text-sm font-semibold">Link do grupo<input required type="url" className={field+' mt-1'} value={form.invite_url} onChange={e=>setForm({...form,invite_url:e.target.value})} placeholder="https://chat.whatsapp.com/..."/></label><label className="block text-sm font-semibold">Categoria<select className={field+' mt-1'} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Achadinhos','Tecnologia','Moda','Casa','Beleza','Geral'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm font-semibold">Observações<textarea maxLength={500} className={field+' mt-1'} rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Regras e horários preferidos"/></label><button disabled={saving} className={action+' flex items-center gap-2'}><Plus size={17}/> Adicionar grupo</button></form></section><section className="zap-card rounded-2xl bg-white p-6"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-black">Meus grupos</h3><span className="text-xs text-slate-500">{loading?'Atualizando...':groups.length+' cadastrados'}</span></div>{!groups.length?<p className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Nenhum grupo cadastrado ainda.</p>:<div className="space-y-3">{groups.map(g=><div key={g.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-800"><MessageCircle size={20}/></div><div className="min-w-0 flex-1"><p className="font-bold">{g.name}</p><p className="text-xs text-slate-500">{g.category} · {g.active?'Ativo':'Pausado'}</p>{g.notes&&<p className="mt-2 text-xs text-slate-500">{g.notes}</p>}</div><button onClick={()=>deleteGroup(g)} title="Excluir grupo" className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div><div className="mt-3 flex flex-wrap gap-2"><a className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold" href={g.invite_url} target="_blank" rel="noopener noreferrer">Abrir grupo <ExternalLink size={13}/></a><button className="rounded-lg border px-3 py-2 text-xs font-bold" onClick={()=>toggleGroup(g)}>{g.active?'Pausar':'Ativar'}</button></div></div>)}</div>}</section></div>
 <section className="zap-card rounded-2xl bg-white p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">CAMPANHAS</p><h3 className="mt-1 text-xl font-black">Agendar uma oferta</h3><p className="mt-2 text-sm text-slate-500">Escolha o produto e os grupos. Você receberá a mensagem pronta para copiar no horário planejado.</p></div><div className="grid gap-5 lg:grid-cols-2"><div className="space-y-4"><label className="block text-sm font-bold">Produto<select className={field+' mt-1'} value={productId} onChange={e=>chooseProduct(e.target.value)}><option value="">Selecione um produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block text-sm font-bold">Data e hora<input type="datetime-local" className={field+' mt-1'} value={when} onChange={e=>setWhen(e.target.value)}/></label><div><p className="mb-2 text-sm font-bold">Enviar para</p><div className="space-y-2">{groups.filter(g=>g.active).map(g=><label key={g.id} className="flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={selectedGroups.includes(g.id)} onChange={e=>setSelectedGroups(v=>e.target.checked?[...v,g.id]:v.filter(id=>id!==g.id))}/>{g.name}</label>)}{!groups.some(g=>g.active)&&<p className="text-sm text-slate-500">Cadastre um grupo ativo primeiro.</p>}</div></div></div><div className="space-y-3"><label className="block text-sm font-bold">Mensagem<textarea className={field+' mt-1'} rows={9} maxLength={4000} value={copy} onChange={e=>setCopy(e.target.value)} placeholder="Selecione um produto para gerar uma mensagem editável."/></label><button className={action+' w-full'} disabled={saving||!groups.some(g=>g.active)} onClick={schedule}>Agendar para {selectedGroups.length} grupo(s)</button><p className="text-xs text-slate-500">Não há envio automático nem acesso às mensagens ou aos membros dos grupos.</p></div></div></section>
 <section className="zap-card rounded-2xl bg-white p-6"><h3 className="mb-4 text-xl font-black">Agenda dos grupos</h3>{!campaigns.length?<p className="text-sm text-slate-500">Nenhuma publicação agendada.</p>:<div className="space-y-3">{campaigns.map(c=>{const g=groups.find(g=>g.id===c.group_id);return <div key={c.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold">{c.product_name}</p><p className="mt-1 text-sm text-slate-500">{g?.name||'Grupo excluído'} · {formatDate(c.scheduled_at)}</p></div><span className={'rounded-full px-3 py-1 text-xs font-bold '+(c.status==='sent'?'bg-emerald-100 text-emerald-800':c.status==='canceled'?'bg-slate-100 text-slate-500':'bg-amber-100 text-amber-800')}>{c.status==='sent'?'Concluído':c.status==='canceled'?'Cancelado':'Agendado'}</span></div>{c.status==='scheduled'&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>navigator.clipboard.writeText(c.message).then(()=>setMessage('Mensagem copiada.'))} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold"><Copy size={14}/> Copiar mensagem</button>{g&&<a href={g.invite_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold">Abrir grupo <ExternalLink size={14}/></a>}<button onClick={()=>updateCampaign(c,'sent')} className="inline-flex items-center gap-1 rounded-xl bg-emerald-800 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 size={14}/> Marcar como enviado</button><button onClick={()=>updateCampaign(c,'canceled')} className="rounded-xl border px-3 py-2 text-xs font-bold text-slate-500">Cancelar</button></div>}</div>})}</div>}</section></div>
}
