import Link from 'next/link'
import type {Metadata} from 'next'
import {ArrowRight,ArrowUpRight,BarChart3,Bot,CalendarDays,Check,ChevronRight,Layers3,Menu,MousePointerClick,Package,ShieldCheck,Store,Target,TrendingUp,Zap} from 'lucide-react'
import './landing.css'
export const metadata:Metadata={title:'Zap OfertasPro | Sua central de oportunidades para afiliados',description:'Organize produtos, explore oportunidades com IA, prepare anúncios e publique sua vitrine. Conheça os planos do Zap OfertasPro.'}
const features=[{icon:Target,title:'Minerador IA',desc:'Explore nichos, faixas de preço e analise produtos antes de divulgar. Uma segunda opinião para escolher seus próximos achadinhos.'},{icon:Package,title:'Catálogo inteligente',desc:'Organize seus produtos, preços, links de afiliado e categorias em um só lugar.'},{icon:Layers3,title:'Anúncios organizados',desc:'Prepare textos para WhatsApp e Instagram e mantenha suas campanhas prontas para publicar.'},{icon:CalendarDays,title:'Calendário de ofertas',desc:'Planeje suas próximas publicações e acompanhe o que está pendente.'},{icon:Store,title:'Sua própria vitrine',desc:'Reúna seus achadinhos em um link para compartilhar com seu público.'},{icon:BarChart3,title:'Visão do negócio',desc:'Visualize seus produtos, anúncios, agendamentos e cliques registrados na vitrine.'}]
const pro=['40 análises exploratórias com IA por mês','Organização de produtos e links','Criação de textos para anúncios','Calendário e vitrine de ofertas']
const premium=['100 análises exploratórias com IA por mês','Organização de produtos e links','Criação de textos para anúncios','Calendário e vitrine de ofertas']
export default function Landing(){
return <div className="lp">
<header className="lp-nav"><div className="lp-wrap lp-nav-inner"><Link className="lp-logo" href="/conhecer" aria-label="Zap OfertasPro início"><span className="lp-logo-icon">Z<span>.</span></span><span>zap<span>ofertas</span><small>PRO STUDIO</small></span></Link><nav aria-label="Navegação principal"><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#planos">Planos</a></nav><Link className="lp-nav-cta" href="/">Acessar plataforma <ArrowUpRight size={17}/></Link></div></header>
<main>
<section className="lp-hero lp-wrap"><div className="lp-hero-copy"><span className="lp-eyebrow"><span className="lp-live"/> O SEU NOVO QG DE OFERTAS</span><h1>Não basta achar ofertas. <em>É preciso enxergar oportunidades.</em></h1><p>Pesquise ideias com IA, organize seus achadinhos, prepare campanhas e tenha sua própria vitrine. Tudo em um painel feito para quem vive de divulgar produtos.</p><div className="lp-actions"><Link href="/" className="lp-primary">Começar teste grátis <ArrowRight size={19}/></Link><a href="#demonstracao" className="lp-secondary">Conhecer a plataforma <ChevronRight size={19}/></a></div><div className="lp-hero-foot"><span><Check size={15}/> Teste grátis de 60 dias</span><span><Check size={15}/> Sem promessas de ganhos</span><span><Check size={15}/> Feito para afiliados</span></div></div><div className="lp-hero-glow" aria-hidden="true"/><div className="lp-hero-index" aria-hidden="true">01 / EXPLORE · ORGANIZE · DIVULGUE</div></section>
<section id="demonstracao" className="lp-preview lp-wrap"><div className="lp-preview-top"><span><i/> ZAP OFERTASPRO / WORKSPACE</span><span>VISÃO GERAL <span className="lp-preview-dot">●</span></span></div><div className="lp-preview-body"><aside className="lp-preview-side"><div className="lp-preview-brand"><span>Z.</span> zap<span>ofertas</span></div><div className="lp-preview-label">WORKSPACE</div><div className="lp-preview-link active">◈ <span>Visão geral</span></div><div className="lp-preview-link">▣ <span>Produtos</span></div><div className="lp-preview-link">⌁ <span>Minerador IA</span></div><div className="lp-preview-link">▤ <span>Anúncios</span></div><div className="lp-preview-link">▦ <span>Calendário</span></div><div className="lp-preview-link">◇ <span>Vitrine</span></div></aside><div className="lp-preview-main"><div className="lp-preview-heading"><div><span>SEU CENTRO DE COMANDO</span><h3>Visão geral</h3></div><span className="lp-preview-status">● ONLINE</span></div><div className="lp-preview-banner"><div><span className="lp-preview-tag">◈ CENTRAL DE OFERTAS</span><h3>Transforme achadinhos em <strong>oportunidades.</strong></h3><p>Produtos, campanhas e sua vitrine em um único espaço.</p><span className="lp-preview-button">+ Adicionar produto</span></div><div className="lp-preview-radar" aria-hidden="true"><div><span>OFERTAS</span></div></div></div><div className="lp-preview-stats"><div><span>PRODUTOS</span><strong>▣</strong><p>Seu catálogo</p></div><div><span>MINERADOR IA</span><strong>⌁</strong><p>Novas ideias</p></div><div><span>ANÚNCIOS</span><strong>▤</strong><p>Suas campanhas</p></div></div></div></div><div className="lp-preview-caption">Uma demonstração ilustrativa do visual da plataforma. Os números e elementos exibidos não representam resultados de usuários.</div></section>
<section className="lp-section lp-wrap" id="recursos"><div className="lp-section-heading"><span className="lp-kicker">[ TUDO NO MESMO LUGAR ]</span><h2>Menos abas abertas.<br/><em>Mais clareza para agir.</em></h2><p>Do primeiro produto à sua vitrine, uma estrutura para tirar suas ofertas do improviso.</p></div><div className="lp-feature-grid">{features.map(({icon:Icon,title,desc},i)=><article className="lp-feature" key={title}><div className="lp-feature-head"><span className="lp-feature-icon"><Icon size={24} strokeWidth={1.7}/></span><span className="lp-feature-number">0{i+1}</span></div><h3>{title}</h3><p>{desc}</p><span className="lp-feature-arrow"><ArrowUpRight size={21}/></span></article>)}</div><p className="lp-disclaimer">O Minerador IA oferece análise exploratória. Preços, avaliações, vendas e comissões atuais devem ser conferidos no marketplace; não há mineração automática em tempo real nesta versão.</p></section>
<section className="lp-how" id="como-funciona"><div className="lp-wrap lp-how-inner"><div><span className="lp-kicker">[ SIMPLES DE COMEÇAR ]</span><h2>Da ideia à divulgação. <em>Sem perder o fio.</em></h2><p>Um fluxo claro para organizar sua operação de afiliado.</p><Link href="/" className="lp-primary">Criar minha conta <ArrowRight size={19}/></Link></div><div className="lp-steps"><div><span>01</span><div><h3>Explore possibilidades</h3><p>Peça à IA ideias por nicho ou analise um produto que você já encontrou.</p></div><Target size={24}/></div><div><span>02</span><div><h3>Monte seu catálogo</h3><p>Cadastre seus links, preços e produtos para manter tudo organizado.</p></div><Package size={24}/></div><div><span>03</span><div><h3>Prepare e compartilhe</h3><p>Crie textos, organize seu calendário e divulgue sua vitrine.</p></div><MousePointerClick size={24}/></div></div></div></section>
<section className="lp-section lp-wrap" id="planos"><div className="lp-section-heading lp-center"><span className="lp-kicker">[ PLANOS ]</span><h2>Escolha seu ritmo.<br/><em>Comece a explorar.</em></h2><p>Experimente a plataforma por 60 dias. Você pode optar por uma assinatura paga diretamente na sua conta.</p></div><div className="lp-pricing"><article className="lp-price"><div className="lp-price-head"><span>PRO / PARA COMEÇAR</span><Zap size={25}/></div><h3>Pro</h3><div className="lp-amount"><span>R$</span>29,90<small>/mês</small></div><p>Para quem quer estruturar sua rotina de achadinhos.</p><Link className="lp-price-button" href="/">Começar teste grátis <ArrowRight size={18}/></Link><ul>{pro.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></article><article className="lp-price featured"><div className="lp-price-ribbon">MAIS ANÁLISES COM IA</div><div className="lp-price-head"><span>PREMIUM / PARA EXPLORAR MAIS</span><TrendingUp size={25}/></div><h3>Premium</h3><div className="lp-amount"><span>R$</span>59,90<small>/mês</small></div><p>Para quem quer pesquisar mais oportunidades com IA.</p><Link className="lp-price-button" href="/">Começar teste grátis <ArrowRight size={18}/></Link><ul>{premium.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></article></div><p className="lp-price-note">O teste grátis não exige a compra imediata de um plano. Se você decidir assinar durante o teste, a cobrança começa no momento da contratação. Consulte os detalhes no aplicativo.</p></section>
<section className="lp-final lp-wrap"><div className="lp-final-orbit" aria-hidden="true"/><span className="lp-kicker">[ SEU PRÓXIMO PASSO ]</span><h2>Seu próximo achadinho merece <em>uma operação à altura.</em></h2><p>Entre no Zap OfertasPro e comece a organizar seus produtos, campanhas e ideias em um só lugar.</p><Link className="lp-primary" href="/">Experimentar grátis <ArrowRight size={19}/></Link></section>
</main><footer className="lp-footer"><div className="lp-wrap"><div className="lp-footer-top"><Link className="lp-logo" href="/conhecer"><span className="lp-logo-icon">Z<span>.</span></span><span>zap<span>ofertas</span><small>PRO STUDIO</small></span></Link><div><a href="#recursos">Recursos</a><a href="#planos">Planos</a><Link href="/">Entrar</Link></div></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Zap OfertasPro. Todos os direitos reservados.</span><span>Uma plataforma para organizar sua operação de afiliado. Resultados dependem da sua estratégia.</span></div></div></footer></div>
}